---
title: LoCOS
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: LoCOS
email: locosdeb@yahoo.com
url: https://locosbd.org
description: Loving Care for the Oppressed Society
twitter_username: 
github_username: 
sass:
  style: compressed
category_dir: categories
permalink: "/:categories/:title/"
