---
title: LoCOS
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: LoCOS
email: locosdeb@yahoo.com
url: https://locosbd.github.io
description: 'A Site Starter Materialize Templates for Jekyll

'
twitter_username: 
github_username: 
sass:
  style: compressed
category_dir: "/categories"
